apiVersion: apps/v1
kind: Deployment
metadata:
  name: jwt-deployment
spec:
  selector:
    matchLabels:
      app: jwt
      version: v1
  replicas: 3
  template:
    metadata:
      labels:
        app: jwt
        version: v1
    spec:
      containers:
      - name: jwt-container
        image: kali042/dotnetjwt:1.0.0
        ports:
        - containerPort: 80